spring.application.name=marque

spring.datasource.url=jdbc:postgresql://localhost:5432/sis_4141
spring.datasource.username=postgres
spring.datasource.password=porfi20010609
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
